### ISSUE TITLE
saslpasswd2 triggers bogus log messages ("error deleting entry from sasldb")

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#264]
From: [David Wagner](daw-bugzilla@taverner.cs.berkeley.edu)
Bugzilla-Id: 3117
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by dgtlmoon** [comment]
I can confirm this in `2.1.27~101-g0780600+dfsg-3ubuntu2`

**Comment by sindarina** [comment]
This apparently also still happens with the version that ships in Debian Buster (2.1.27+dfsg-1)

**Comment by macropin** [comment]
I can confirm this with buster and `2.1.27+dfsg-1`. Looks like the error goes to syslog not stdout/err.

**Comment by wioxjk** [comment]
Problem persist in Debian Stretch, Buster and Testing

**Comment by Harryols** [comment]
What is fix?

**Comment by hyc** [comment]
I don't see any such problem in master, anyway.

**Comment by hyc** [comment]
I see, the cause still exists, somewhat, in master. The messages are generated because saslpasswd is unconditionally trying to delete obsolete password records from the DB, as seen here https://github.com/cyrusimap/cyrus-sasl/blob/cyrus-sasl-2.1/utils/saslpasswd.c#L441

The error messages are harmless and should just be ignored.

**Comment by hyc** [comment]
I guess we can just drop that. Anyone have any objections?

**Comment by quanah** [comment]
I have no objection to dropping it.
