### ISSUE TITLE
realm specific configuration for LDAP

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#319]
From: [John Newbigin](jnewbigin@swin.edu.au)
Bugzilla-Id: 3181
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by jdehaan** [comment]
I think this is a really great feature that avoids many quirky workarounds in order to get the same benefits like described here: https://ltb-project.org/documentation/general/sasl_delegation

I do not know if the potential connection caches are ok with that though... These would have to be maintained per realm as well (I am unfamiliar with the internals of the daemon, I am unsure if this is really missing or if there is no cache then also no problem)

**Comment by hyc** [comment]
See back-meta solution in comments of #621
