### ISSUE TITLE
auxprop-hashed with slapd allows any password

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#374]
From: [Pawel Tomulik](ptomulik@meil.pw.edu.pl)
Bugzilla-Id: 3743
Version: 2.1.25
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by quanah** [comment]
This is a pretty serious security bug.  Any updates?  OpenLDAP has been waiting for cyrus-sasl to address this to know if we need to do anything on our side (OpenLDAP issue #7419)

**Comment by whitehse** [comment]
@quanah 

I've reproduced this with 2.1.27 rc6, and OpenLDAP 2.4.45. With 'pwcheck_method: auxprop-hashed':

```bash
~$ ldapwhoami -Y PLAIN -H ldapi:// -U dwheite@example.com -w asefawef
SASL/PLAIN authentication started
SASL username: dwheite@example.com
SASL SSF: 0
dn:uid=dwheite@example.com,cn=plain,cn=auth
```

and with the identical setup, but with 'pwcheck_method: auxprop':

```bash
~$ ldapwhoami -Y PLAIN -H ldapi:// -U dwheite@example.com -w asefawef
SASL/PLAIN authentication started
ldap_sasl_interactive_bind_s: Invalid credentials (49)
        additional info: SASL(-13): user not found: Password verification failed
```

I'll further investigate.

**Comment by hyc** [comment]
slapd does not advertise support for auxprop-hashed validation, so sasl should not be trying to do it here.

**Comment by hyc** [comment]
Basically the design for hashed password support introduced in 62ce0768aa375cf0d16102570970b232dcb1cb28 is broken since it doesn't actually check whether the auxprop plugin supports it. And that commit only updated sasldb to support it, meaning using any other plugin would break in the same way as described here. Fixing this securely will require redesigning this part of the API.

**Comment by hyc** [comment]
Noting that there is zero documentation for this auxprop-hashed feature. `git grep auxprop-hashed` returns only 2 hits in the entire source tree. Reading the code doesn't reveal anywhere that password hashing occurs, so I'd have to assume the auxprop module is supposed to hash for you, but the auxprop_verify_password_hashed() function only does a strcmp on the returned value, which implies that the input password must already be hashed, which makes no sense. |I can only conclude that this code has never worked. @aamelnikov can you please point to any documentation on what this feature is meant to do and how it works?

**Comment by hyc** [comment]
OK, to summarize what we've found: this "feature" works by setting the `SASL_AUXPROP_VERIFY_AGAINST_HASH` flag on an auxprop query, and passing in the user-provided plaintext password. The auxprop plugin is expected to validate against whatever password hash it uses, and zero out the passed in password on mismatch, or leave it unchanged on success.

Which is, as noted above, a completely braindead design, especially in security software. Basically it defaults to success for all existing plugins that don't know about the `SASL_AUXPROP_VERIFY_AGAINST_HASH` flag. Which is the majority of them. Utterly insecure design and grossly irresponsible for it to have ever gone into the code base. We are disabling the feature for now. Can revisit in a future release to do it properly so that it defaults to failure for plugins that don't recognize the feature.
