### ISSUE TITLE
OpenSSL 1.1.0 support

### ISSUE THREAD

**Issue by oerdnj** [cyrusimap/cyrus-sasl#4]
Debian Stretch (and possibly other distributions) are going to switch to OpenSSL 1.1.0.

Building with OpenSSL 1.1.0 breaks, so adding support to 2.1.x branch would be much appreciated. The original bug report and build log can be found here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828139

**Comment by elliefm** [comment]
The only errors I get when linking with OpenSSL 1.1.0 are from plugins/otp.c

Both errors are due to stack allocations of EVP_MD_CTX, which in OpenSSL 1.1.0 is an opaque type of unknown size, so can't be allocated on the stack.

It can be fixed for OpenSSL 1.1.0 by changing `EVP_MD_CTX mdctx;` to `EVP_MD_CTX *mdctx;`, by allocating and deallocating it with `EVP_MD_CTX_new()` and `EVP_MD_CTX_free()`, and by removing the dereferences from the calls to `EVP_Digest*()`.  You need to do all this in two places: `otp_hash()` and `word2bin()`.

But!

* `otp_hash()` returns void, so there's no way to report failure to the caller if `EVP_MD_CTX_new()` fails. (`word2bin()` returns int, so it can happily return `SASL_NOMEM` in this case.)
* `EVP_MD_CTX_new()` and `...free()` are new in OpenSSL 1.1.0, so this particular fix breaks support for current/earlier OpenSSL versions.

The latter might have been trivially worked around by providing our own `EVP_MD_CTX_new()` and `EVP_MD_CTX_free()` implementations for older OpenSSLs (like we did with `DH_set0_pqg()` in cyrus-imapd), except that from the looks of things, SASL plugins want to use `utils->malloc()` for allocations, which means we need to pass in a `const sasl_utils_t *`, so it can't just be a drop-in replacement.

Instead of providing our own `EVP_MD_CTX_new()/free()`, we could instead have both implementations in these two places, conditionally selected (so that we use a stack-allocated EVP_MD_CTX with old OpenSSL, and a dynamically-allocated one with new OpenSSL).  This solves the issue of being unable to pass around a sasl_utils_t.  But it doesn't solve the issue of `otp_hash()` being unable to indicate allocation failure to its caller.  And it maybe introduces a new issue, with OpenSSL using its own allocator rather than the one from sasl_utils_t?

@ksmurchison, I'm out of my depth here, what's the appropriate way for a SASL plugin to handle this?

**Comment by ksmurchison** [comment]
I will have to take a look.

**Comment by ksmurchison** [comment]
Fixed with commit 
https://github.com/cyrusimap/cyrus-sasl/commit/4c8e3f24bb943386a67b4de65bb849f562499dd0
