### ISSUE TITLE
cyrusimap.org releases missing old cyrus-sasl releases

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#453]
Not a code issue, but there are no old releases for cyrus-sasl at https://www.cyrusimap.org/releases/old/

**Comment by Jakuje** [comment]
The older versions are for example here:
ftp://ftp.cyrusimap.org/cyrus-sasl/

This url is already listed in the README so I believe it is ok.

**Comment by quanah** [comment]
That leads to a more interesting question -- Why are there two utterly separate distribution points? And the web location is consistent as compared to the FTP site for cyrus-imapd.  It's only cyrus-sasl that differs.

**Comment by elliefm** [comment]
The oldest timestamps in there (including for cyrus-sasl-2.1.26.tar.gz) are around 2012, so I'd infer that at some point the directory structure was rearranged or rebuilt, and the web server only has the files since then?  It could also be that releases were FTP-only prior to 2012?  But I've got no idea really, that was long before I came on board.

@ajaysusarla, do you have some time to copy the older sasl releases over from the FTP to the website?  I'm still without proper internet at the new place until next week sometime.  If there's no .sig files already, don't bother creating them -- you and I have no idea what those tarballs contain so we shouldn't sign them with our keys. ;)

I imagine all this will be rehomed at some point in the near future -- at this stage the website and ftp are still hosted on CMU infrastructure I believe.  Longer term, I'd be in favour of ditching FTP altogether and serving HTTPS-only, for whatever that's worth.

**Comment by ajaysusarla** [comment]
@elliefm I'll get this done. Thanks!

**Comment by ajaysusarla** [comment]
All the old `cyrus-sasl` release are now available at `https://www.cyrusimap.org/releases/old/`. List of `cyrus-sasl` files:
```
cyrus-sasl-1.5.28.tar.gz 
cyrus-sasl-1.5.28.tar.gz.sig 
cyrus-sasl-2.1.19.tar.gz  
cyrus-sasl-2.1.19.tar.gz.sig    
cyrus-sasl-2.1.20.tar.gz    
cyrus-sasl-2.1.20.tar.gz.sig 
cyrus-sasl-2.1.21.tar.gz    
cyrus-sasl-2.1.21.tar.gz.sig    
cyrus-sasl-2.1.22.tar.gz  
cyrus-sasl-2.1.22.tar.gz.sig    
cyrus-sasl-2.1.23.tar.gz    
cyrus-sasl-2.1.23.tar.gz.sig     
cyrus-sasl-2.1.24rc1.tar.gz    
cyrus-sasl-2.1.24rc1.tar.gz.sig  
cyrus-sasl-2.1.25.tar.gz
cyrus-sasl-2.1.25.tar.gz.sig
cyrus-sasl-2.1.26.tar.gz 
```
