### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [cyrusimap/cyrus-sasl#580]
I think that after almost of the development it would be good to flush currently committed changes and make new release :)

**Comment by kloczek** [comment]
It would be good to change as well tagging convension from cyrus-sasl-<version> to only <version>
because autogenerated bby github tat ball from https://github.com/cyrusimap/cyrus-sasl//archive/cyrus-sasl-2.1.27.tar.gz has as base top directory cyrus-sasl-cyrus-sasl-2.1.27.

**Comment by Neustradamus** [comment]
@elliefm: It is possible to create a new version, a 2.1.28?
Already one year without a new build, ...

**Comment by quanah** [comment]
I've never even gotten the last release to work reliably, which was cut w/o warning and missed items that had been marked for inclusion.  Add to that the fact there's now a publicly posted security bug... https://github.com/cyrusimap/cyrus-sasl/issues/587

**Comment by elliefm** [comment]
> which was cut w/o warning 

There were 7 release candidates published before 2.1.27 was finally released...

> It is possible to create a new version, a 2.1.28?

I have no idea, I don't know this code at all.  Looking at commit history, it looks like @aamelnikov has done most of the recent work on it, but I don't know if they use github.

>  cyrus-sasl-cyrus-sasl-2.1.27

Yeah, that's weird.  The tags probably won't change, but I wonder if the distribution process has a bug in it.

**Comment by quanah** [comment]
@elliefm There was an email explicitly stating there would be one more beta BEFORE release.  Instead, the release was just dropped w/o warning.

**Comment by Neustradamus** [comment]
@elliefm: It is possible to change tags:
- https://github.com/cyrusimap/cyrus-sasl/tags

Example:
- https://github.com/cyrusimap/cyrus-sasl/releases/tag/cyrus-sasl-2.1.27
->
- https://github.com/cyrusimap/cyrus-sasl/releases/tag/v2.1.27

So you can create a 2.1.27.1 or 2.1.28 Beta 1 or RC1... :)
Badly it is impossible to release a new version with all bugs solves some are 20 years old.

In the same time, why Debian has not SCRAM-SHA-1 which is supported since a long time?
- https://packages.debian.org/en/jessie/libsasl2-2
- https://packages.debian.org/en/stretch/libsasl2-2
- https://packages.debian.org/en/buster/libsasl2-2
- https://packages.debian.org/en/bullseye/libsasl2-2
- https://packages.debian.org/en/sid/libsasl2-2
-> @rcsanchez97 @oerdnj ??
Linked to: https://bugs.exim.org/show_bug.cgi?id=2349#c6

Can you look for website problems:
- https://github.com/cyrusimap/cyrus-sasl/issues/549#issuecomment-553148150

And do not forget PR: https://github.com/cyrusimap/cyrus-sasl/pulls

**Comment by elliefm** [comment]
Yes, I know how the github workflows work.  This project (cyrus-sasl) doesn't seem to really use them though, as you might guess, by the number of ignored issues and pull requests on here.

I don't know this project, and I don't really look at it.  I'm only here now because you tagged me, presumably because my name was on the last release (which is only because I was the one who uploaded it to github and sent out the email/etc).

I'm going to see if I can add a banner to the top of the https://github.com/cyrusimap/cyrus-sasl page directing people to the Cyrus-SASL mailing list, because it seems like it might be a more effective means of reaching the community than posting here, and also fix the readme for the same.

**Comment by Neustradamus** [comment]
@rcsanchez97 @rsanchez-wsu @robertocsanchez @oerdnj

When do you will reply?

I see changes in Debian but not for SCRAM!

Any news??

It is really important...

**Comment by rcsanchez97** [comment]
@Neustradamus I'm afraid I don't understand what you mean.  The current version in Debian unstable, testing, and stable is the latest upstream release (2.1.27).  Is there a problem with those packages.  If so, is there a bug in the Debian BTS documenting the issue?

**Comment by okias** [comment]
Is any reason why cyrus maintainers are reluctant to release new version and keep all patching & CVE fixes burden on distribution maintainers instead releasing new version?

In case this thread will get no reply & action, would anyone with Cyrus-IMAP knowledge fork it and continue merging PR & CVE-fixes and make releases?

**Comment by quanah** [comment]
I'm not clear why you are bringing up cyrus-imap here?

**Comment by okias** [comment]
@quanah typo, sorry

**Comment by quanah** [comment]
@okias Ok. The major issue right now in regards to doing a new release is that accepting contributions is a minefield at the moment.  Once that is resolved and I can provide proper guidance to PRs on the terms contributions can be accepted (and possible license updates to the code base itself) we can look at a new release.

**Comment by quanah** [comment]
Looks like the re-license is on hold.  I'm working on what the process is for contributions (rights assignments, etc) so I can start working on the MRs.

**Comment by bmanahilov** [comment]
Hi team, thank you for the effort updating the library. Do you have any plan for a 2.1.28 or 2.1.27.1 including the CVE-2019-19906 fix?
Thanks.

**Comment by quanah** [comment]
We are working on a 2.1.28.

**Comment by kloczek** [comment]
Gentle ping .. any update?😄

**Comment by quanah** [comment]
We're close :) I'm in the middle of a job transition so that's slowing things down.  Primarily I'm working on current documentation on how to actually do a release because the existing docs are a decade or so out of date and inapplicable.

**Comment by quanah** [comment]
2.1.28 released, closing

**Comment by Neustradamus** [comment]
@quanah: Thanks to you and others for this new Cyrus SASL "2.1.28" version!
3 years and 3 months after 2.1.27 ^^

**Comment by Neustradamus** [comment]
Dear all,

Latest Cyrus-SASL is 2.1.28 (2022-02-22), soon 3 years.

Can you go here for talk about a new version before Debian 13 freeze soon?

Next Debian 14 will be in 2027:
- https://github.com/cyrusimap/cyrus-sasl/issues/835

Thanks in advance.
