### ISSUE TITLE
[Question] License clarification

### ISSUE THREAD

**Issue by prehistoric-penguin** [cyrusimap/cyrus-sasl#594]
I know that there is a coping file: https://github.com/cyrusimap/cyrus-sasl/blob/master/COPYING

But I'm not sure what the kind is this license exactly(Someone in [SO](https://stackoverflow.com/questions/32246699/build-cyrus-sasl-as-static-library-on-windows) said that it's AGPL, in the comment of the question),  could you please give us a clear clarification, is this GPL or BSD? Can I shift it with our product without publishing all my source code?

**Comment by flowerysong** [comment]
It's not AGPL, so the StackOverflow person is probably thinking of some other SASL implementation.

The license is the license in the file, which is not a standard, widely-used license. It's broadly in the same family as BSD and MIT, but if you have worries about your specific rights and responsibilities under the license that are not answered by reading it, you should consult a legal expert rather than the internet.

**Comment by quanah** [comment]
It's a BSD 4-clause style license.

**Comment by pmhahn** [comment]
> It's a BSD 4-clause style license.

No, more like [BSD-3-Clause-Attribution](https://spdx.org/licenses/BSD-3-Clause-Attribution.html) but with small variatios. The even older [BSD-4-Clause](https://spdx.org/licenses/BSD-4-Clause.html) differs manly in clause 3 and 4:

| [Cyrus](https://github.com/cyrusimap/cyrus-sasl/blob/master/COPYING) | [BSD-3-Clause-Attribution](https://spdx.org/licenses/BSD-3-Clause-Attribution.html) | [BSD-4-Clause](https://spdx.org/licenses/BSD-4-Clause.html) |
| --- | --- | --- |
| — | — | 3. All advertising materials mentioning features or use of this software must display the following acknowledgement: This product includes software developed by the organization. |
| 3. The name "CMU" must not be used to endorse or promote products derived from this software without prior written permission. For permission or any other legal details, please contact … | 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. | 4. Neither the name of the copyright holder nor the names the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. |
| 4. Redistributions of any form whatsoever must retain the following acknowledgment: "This product includes software developed by …" | 4. Redistributions of any form whatsoever must retain the following acknowledgment: 'This product includes software developed by …' | — |

(redacted by me for brevity)

Sadly BSD-3-A is still GPL-incompatible because of that acknowledgement requirement, even it its lesser form. This lead to [Debian Bug #996892](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996892), where Debian is asked to declare SASL a "system library" to allow other GPL-3-licensed packages to use SASL.

Is there a chance to re-license  SASL under — for example — [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause-Attribution.html) by dropping the _acknowledgement requirement_ as mentioned in [The BSD License Problem](https://www.gnu.org/licenses/bsd.html.en)?

**Comment by quanah** [comment]
You'd need to talk to CMU legal

**Comment by pmhahn** [comment]
> You'd need to talk to CMU legal

Thanks you for the reply. Can you provide a contact as `tech-transfer@andrew.cmu.edu` mentioned in [COPYING](https://github.com/cyrusimap/cyrus-sasl/blob/master/COPYING) is unreachable and https://www.cmu.edu/legal/ did not return any contact.

**Comment by bgermann** [comment]
innovation (at) cmu (dot) edu

**Comment by rlaager** [comment]
While getting CMU to drop the clause would be best, as it avoids ambiguity, I don't think BSD-3-Clause-Attribution is GPL-incompatible.

**Comment by pmhahn** [comment]
> While getting CMU to drop the clause would be best, as it avoids ambiguity, I don't think BSD-3-Clause-Attribution is GPL-incompatible.

Unless you're a lawyer please go to [BSD-3-Clause-Attribution](https://spdx.org/licenses/BSD-3-Clause-Attribution.html) and follow the link to [fedoraproject.og](https://fedoraproject.org/wiki/Licensing/BSD_with_Attribution) which has this statement:

> This license is identical to BSD, with the exception of clause 4. Clause 4 adds an "attribution" requirement, not to be confused with the "advertising" clause found in older BSD license texts. This license was noticed in cyrus-sasl and UpTools. It is Free, but GPL compatibility is unclear at this time.

I'm not a lawyer myself but others still consider BSD3CA to be a serious problem: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996892
A customer of my company with its own legal department also asked for this explicitly.

PS: So far no progress with CMU: Albeit I got a response, my attempt to contact the original authors of SASL failed. While doing more research I found that  [Fastmail tried to get the licence transferred](https://www.mail-archive.com/cyrus-sasl@lists.andrew.cmu.edu/msg02601.html) ~2020.

**Comment by stefan6419846** [comment]
Apart from the issues with BSD-Attribution-HPND-disclaimer (the [SPDX identifier](https://spdx.org/licenses/BSD-Attribution-HPND-disclaimer.html) linking to the license of this repository), there possibly are further issues (checked on the current `master`):

* OpenSSL
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/common/crypto-compat.c
  * Refers to the OpenSSL license, which is no clear statement. From the history, it seems like this means the OpenSSL SPDX ID for OpenSSL < 3.0, which is considered incompatible with the GPL.
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/kerberos_includes/kerberos/des.h refers to the problematic SSLeay license part of OpenSSL.
* APSL-1.1
  * https://github.com/cyrusimap/cyrus-sasl/tree/master/dlcompat-20010505
  * The APSL-1.1 is considered incompatible with the GPL as well.
* BSD-4-Clause-UC
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/include/exits.h
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/lib/getsubopt.c
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/mac_lib/getopt.c
  * Has indeed a real advertisement clause and tends to be incompatible as well.
* BSD-4-Clause
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/krb4_sources/lsb_addr_comp.c
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/krb4_sources/krb-protos.h
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/krb4_sources/mk_req.c
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/krb4_sources/mk_safe.c
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/krb4_sources/rd_priv.c
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/krb4_sources/rd_safe.c
  * https://github.com/cyrusimap/cyrus-sasl/blob/master/mac/krb4_sources/rw.c
  * Has indeed a real advertisement clause and tends to be incompatible as well.

The latest release includes the possibly incompatible RSA-MD license as well for the MD5 implementation as well as possibly some more/other files being subject to the aforementioned licenses.

Disclaimer: IANAL and the aforementioned list might be incomplete or have other limitations.

**Comment by bgermann** [comment]
BSD-4-Clause-UC does not have a "real advertisement clause" anymore because there was a copyright addendum. That is the point of the "-UC" part in its name.

**Comment by bgermann** [comment]
The other files are optional and can be excluded easily, which is done in Debian's cyrus-sasl2 package for example.
