### ISSUE TITLE
A potential bug of NPD

### ISSUE THREAD

**Issue by ash1852** [cyrusimap/cyrus-sasl#744]
Hi,I found a potential bug of null pointer dereference in source code of sasl,in the **line 37** of file sasl//sample/http_digest_client.c, there is a combined use of **getuid()** and **getpwuid(uid)** and then derefer it to get field **pw_name**, according to [the document of getpwuid](https://pubs.opengroup.org/onlinepubs/009696799/functions/getpwuid.html),it is possible that getpwuid may return null and change **errno** to corresponding error number.This error is possible and many examples can be found using search engines like google.

In my humble opinion, it is more safer to judge return value after using getpwuid, and handle it according to the value of errno.

https://github.com/cyrusimap/cyrus-sasl/blob/61e358da45d1740a722058d74aaecde76ae0abb0/sample/http_digest_client.c#L36-L39

**Comment by hyc** [comment]
Since this is just a sample program it doesn't really matter. Of the possible errors listed, EMFILE / ENFILE cannot occur unless a user has intentionally set the limit to a number smaller than 4. ENOMEM cannot occur since getpwuid() returns a pointer to a static buffer. EINTR cannot occur because the program doesn't catch any signals. EIO could occur if the OS or storage device is hosed, but in that case the program may as well crash anyway.

**Comment by ash1852** [comment]
thanks
