### ISSUE TITLE
Create a target for making the sasl docs

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-sasl#9]
The same as for cyrus-imapd, we need a target in the toplevel sasl Makefile to create the html docs from the rst ones and put them somewhere so they can get packaged for releases.

@elliefm for makefile/configure shenanigans
@ksmurchison for actual release handling once he can build the html

**Comment by ksmurchison** [comment]
make dist is currently working and I have a pre-release out there for testing.  I'm looking at work autoconf foo is needed for docs but may need some help

**Comment by ksmurchison** [comment]
I added the autoconf detection stuff.  Now to look at Makefile.am

**Comment by ksmurchison** [comment]
@elliefm  I could use some help with the Makefile target(s) if you have time

**Comment by elliefm** [comment]
Have been meaning to have a look, but haven't yet, will try and look this week.  Feel free to nag if I forget :)

**Comment by elliefm** [comment]
@ksmurchison does sasl have any docs that are generated, ala imapd.conf.5 in imapd?

**Comment by ksmurchison** [comment]
@elliefm None that I recall.  Just stuff in doc/ and man/.  It looks like @nicolan already moved some stuff into docsrc/

**Comment by elliefm** [comment]
The recursive make setup that sasl uses might complicate this a bit (vs imapd's single top level makefile).  I'm loathe to make as sweeping a change as to convert it into a single makefile, because I don't know the project particularly well at all and I'll probably break a hundred things -- I notice there's a separate make setup for NT for example.

`make distcheck` currently fails, which is frustrating, cause it means I can't use it to verify that I haven't broken the distribution after I make changes.

I won't push any changes up myself -- I've forked and I'm experimenting/working on a branch on that.  I'll submit a pull request for review once I have an approach that seems workable, and we can refine from there

**Comment by elliefm** [comment]
`make dist` also currently fails for me:

```
make[3]: Entering directory '/home/ellie/fastmail/cyrus-sasl/java/CyrusSasl'
CLASSPATH=:./${CLASSPATH:+":$CLASSPATH"} true -d     Sasl.java GenericClient.java ClientFactory.java GenericCommon.java SaslClient.java SaslClientFactory.java SaslException.java SaslInputStream.java SaslOutputStream.java SaslUtils.java ServerFactory.java SaslServerFactory.java SaslServer.java GenericServer.java
echo timestamp > classjavasasl.stamp
CLASSPATH=:./${CLASSPATH:+":$CLASSPATH"} true -o javasasl.h -jni CyrusSasl.Sasl CyrusSasl.GenericClient CyrusSasl.ClientFactory CyrusSasl.GenericCommon CyrusSasl.SaslClient CyrusSasl.SaslClientFactory CyrusSasl.SaslException CyrusSasl.SaslInputStream CyrusSasl.SaslOutputStream CyrusSasl.SaslUtils CyrusSasl.ServerFactory CyrusSasl.SaslServerFactory CyrusSasl.SaslServer CyrusSasl.GenericServer
cp: cannot stat './javasasl.h': No such file or directory
Makefile:640: recipe for target 'distdir' failed
make[3]: *** [distdir] Error 1
```

This is after `./autogen.sh --enable-silent-rules --enable-maintainer-mode`

It makes no difference whether I `--enable-maintainer-mode` or not

It makes no difference if I `make` first, or just go straight to `make dist`

This is also the same spot where `make distcheck` failed for me earlier, so maybe there's something I'm missing, either in my process or environment?

**Comment by elliefm** [comment]
Actually, I think those are failing because I'm missing `javah`

**Comment by elliefm** [comment]
@ksmurchison I've rebased my old work in progress branch on top of current master:  https://github.com/elliefm/cyrus-sasl/tree/doc-build

The `make doc` target seems to build the html docs okay (into doc/sasl).  I can't test integration with the distribution though, because I don't have `javah` and can't install it at the moment for Reasons.

Can you run this branch through `make dist` and `make distcheck` please, and let me know whether a) everything works, and b) the generated html docs end up inside the tarball?

**Comment by ksmurchison** [comment]
Make dist works and the HTML docs are included.

I think we're missing a target for docsrc/ as make distcheck fails with this:

make[2]: Entering directory '/tmp/cyrus-sasl/cyrus-sasl-2.1.27/_build/sub'
test x"../.." = x"." || \
        (cd ../.. && tar cf - --mode=gu+w docsrc) | tar xf -
tar: docsrc: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
touch: cannot touch 'docsrc/.sphinx-build.stamp': No such file or directory
Makefile:1053: recipe for target 'docsrc/.sphinx-build.stamp' failed
make[2]: *** [docsrc/.sphinx-build.stamp] Error 1
make[2]: Leaving directory '/tmp/cyrus-sasl/cyrus-sasl-2.1.27/_build/sub'
Makefile:797: recipe for target 'dist' failed

**Comment by nacho** [comment]
missing docsrc in EXTRA_DIST?

**Comment by elliefm** [comment]
Cheers, will add it in.  Will also look at generating the man format manpages, now that @nicolan's converted them to rst.

**Comment by elliefm** [comment]
@ksmurchison my branch has the above in it now, any luck with `make distcheck`?

**Comment by elliefm** [comment]
@ksmurchison my branch is rebased on top of current master again, and I've added support for generating man pages now too.

Could you run this through `make dist` and `make distcheck` again please?  Cheers

**Comment by ksmurchison** [comment]
@elliefm  make dist works

make distcheck needs this commit to get past the build phase: https://github.com/cyrusimap/cyrus-sasl/commit/6179188c06146f0e4fff56acc216f89b1d8dcd70

but still fails here:
Making distclean in plugins
make[2]: Entering directory '/tmp/cyrus-sasl/cyrus-sasl-2.1.27/_build/sub/plugins'
Makefile:697: .deps/anonymous.Plo: No such file or directory
Makefile:698: .deps/anonymous_init.Plo: No such file or directory
Makefile:699: .deps/cram.Plo: No such file or directory
Makefile:700: .deps/crammd5_init.Plo: No such file or directory
Makefile:701: .deps/digestmd5.Plo: No such file or directory
Makefile:702: .deps/digestmd5_init.Plo: No such file or directory
Makefile:703: .deps/gs2.Plo: No such file or directory
Makefile:704: .deps/gs2_init.Plo: No such file or directory
Makefile:705: .deps/gs2_token.Plo: No such file or directory
Makefile:706: .deps/gssapi.Plo: No such file or directory
Makefile:707: .deps/gssapiv2_init.Plo: No such file or directory
Makefile:708: .deps/kerberos4.Plo: No such file or directory
Makefile:709: .deps/kerberos4_init.Plo: No such file or directory
Makefile:710: .deps/ldapdb.Plo: No such file or directory
Makefile:711: .deps/ldapdb_init.Plo: No such file or directory
Makefile:712: .deps/login.Plo: No such file or directory
Makefile:713: .deps/login_init.Plo: No such file or directory
Makefile:714: .deps/ntlm.Plo: No such file or directory
Makefile:715: .deps/ntlm_init.Plo: No such file or directory
Makefile:716: .deps/otp.Plo: No such file or directory
Makefile:717: .deps/otp_init.Plo: No such file or directory
Makefile:718: .deps/passdss.Plo: No such file or directory
Makefile:719: .deps/passdss_init.Plo: No such file or directory
Makefile:720: .deps/plain.Plo: No such file or directory
Makefile:721: .deps/plain_init.Plo: No such file or directory
Makefile:722: .deps/plugin_common.Plo: No such file or directory
Makefile:723: .deps/sasldb.Plo: No such file or directory
Makefile:724: .deps/sasldb_init.Plo: No such file or directory
Makefile:725: .deps/scram.Plo: No such file or directory
Makefile:726: .deps/scram_init.Plo: No such file or directory
Makefile:727: .deps/sql.Plo: No such file or directory
Makefile:728: .deps/sql_init.Plo: No such file or directory
Makefile:729: .deps/srp.Plo: No such file or directory
Makefile:730: .deps/srp_init.Plo: No such file or directory
make[2]: *** No rule to make target '.deps/srp_init.Plo'.  Stop.
make[2]: Leaving directory '/tmp/cyrus-sasl/cyrus-sasl-2.1.27/_build/sub/plugins'
Makefile:684: recipe for target 'distclean-recursive' failed
make[1]: *** [distclean-recursive] Error 1
make[1]: Leaving directory '/tmp/cyrus-sasl/cyrus-sasl-2.1.27/_build/sub'
Makefile:892: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1

This appears to be doing the same as the distclean target, which also fails.  Removing the 'include' lines at the given line numbers allows distclean to complete successfully.  I don't know enough about autoconf/libtool to know why these lines are there, how they get there, or if they are required.

**Comment by elliefm** [comment]
Okay, so the distclean target is broken because `lib/Makefile.am` includes `../plugins/plugin_common.c` in the sources for libsasl2.la.  As a result, automake sets up the distclean target in lib/Makefile to also clean up the `plugins/` directory:

```
Making distclean in lib
make[1]: Entering directory '/home/ellie/fastmail/cyrus-sasl/lib'
test -z "libsasl2.la" || rm -f libsasl2.la
rm -f ./so_locations
rm -rf .libs _libs
rm -rf ../plugins/.libs ../plugins/_libs
test -z "" || rm -f 
test -z "libobj.la" || rm -f libobj.la
rm -f ./so_locations
rm -f *.o
rm -f ../plugins/*.o
rm -f ../plugins/*.lo
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f ../plugins/.deps/.dirstamp
rm -f ../plugins/.dirstamp
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf .deps ../plugins/.deps ./.deps
rm -f Makefile
make[1]: Leaving directory '/home/ellie/fastmail/cyrus-sasl/lib'
```

Note it has rm -rf'd `..plugins/.deps` in there!  So then the `distclean` target in `plugins/Makefile` fails because it expects to be able to include files that no longer exist....

**Comment by elliefm** [comment]
I've tried the obvious thing, and moved "plugins" before "lib" in the top level Makefile.am's `SUBDIRS`, to see if that would affect the compile/clean order -- and it does!  Which might hypothetically fix the distclean target, except that the make target is now broken...

Looks like there's a circular dependency between parts of the `lib` directory and the `plugins` directory, and the current setup (complete with broken distclean) is the compromise to get it to at least build properly.  Not yet sure what the fix would be, other than migrating the whole project into a single top level Makefile.am, which I'm hesitant to do for anything less than a major release.

Though, it looks like all of this has been changed _substantially_ since the 2.1.26 release (9a9907b) so umm, great.  I'll keep fiddling around and see if I can fix it up enough for distclean/distcheck to succeed, but I think in the meantime the current compromise might need to suffice.
